resolver: clash-HEAD.yaml

extra-deps:
  - clash-shake
  - retroclash-lib
  - retroclash-sim

  - barbies-2.0.1.0
  - barbies-th-0.1.2

  - github: gergoerdi/clashilator
    commit: e34b01bc76273167d13697d44d723acb59648062
